# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 18:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(choices=[(b'AL', b'Alav\xc3\xa9s'), (b'AB', b'Athletic'), (b'AM', b'Atl\xc3\xa9tico'), (b'BR', b'Barcelona'), (b'BE', b'Betis'), (b'CE', b'Celta'), (b'DC', b'Deportivo'), (b'EI', b'Eibar'), (b'ES', b'Espanyol'), (b'GR', b'Granada'), (b'LP', b'Las Palmas'), (b'LE', b'Legan\xc3\xa9s'), (b'MA', b'M\xc3\xa1laga'), (b'OS', b'Osasuna'), (b'RM', b'R. Madrid'), (b'RS', b'R. Sociedad'), (b'SE', b'Sevilla'), (b'SP', b'Sporting'), (b'VA', b'Valencia'), (b'VI', b'Villareal')], max_length=2)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
