# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0003_auto_20170104_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='jornada',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
